import type { Metadata } from "next";
import "./globals.css";
import { Body, HTML, Navbar } from "@/components/ui";
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<HTML>
			<Body>
				{/* <Navbar.Root>
					<Navbar.MadeBy />
				</Navbar.Root> */}
				<SpeedInsights />
			</Body>
		</HTML>
	);
}
