name: "Testing to accept Build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  builds:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with: ${{matrix.node-version}}

      - name: Install Dependencies
        run: pnpm i
    
      # - name: Building Next.js and Linting
      #   run: |

